package com.thanhtam.linhsondich.model

import android.content.Context
import android.os.Parcelable
import android.widget.EditText
import android.widget.TextView
import com.thanhtam.linhsondich.R
import kotlinx.android.parcel.Parcelize

@Parcelize
data class model(var _ThuongQuai: Int, var _HaQuai: Int) : Parcelable


//@Parcelize
//data class CanChiNgayThang(
//    var canngay: Int,
//    var chingay: Int,
//    var canthang: Int,
//    var chithang: Int,
//    var cannam: Int,
//    var chinam: Int,
//    var chigio: Int,
//) : Parcelable



@Parcelize
data class Que(
    var tenque: String,
    var h1: Int,
    var h2: Int,
    var h3: Int,
    var h4: Int,
    var h5: Int,
    var h6: Int,
    var tuongque: String,
    var chi1: String,
    var chi2: String,
    var chi3: String,
    var chi4: String,
    var chi5: String,
    var chi6: String,
    var pt1: String,
    var pt2: String,
    var vtpt1: Int,
    var vtpt2: Int,
    var the: Int,
    var cung: String,
    var thuoctinh: String,
    var luangiai: String,
    var loihao1: String,
    var loihao2: String,
    var loihao3: String,
    var loihao4: String,
    var loihao5: String,
    var loihao6: String,
) : Parcelable


data class _Que(
    var h1: Int,
    var h2: Int,
    var h3: Int,
    var h4: Int,
    var h5: Int,
    var h6: Int,
    var context: Context
) {
    var giaique = context.resources.getStringArray(R.array.giaique)
    fun __Que(): Que {
        var ___Que =
            Que(
                "",
                0,
                0,
                0,
                0,
                0,
                0,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                0,
                0,
                0,
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
                "",
            )
        if (h1 == 0 && h2 == 0 && h3 == 0 && h4 == 0 && h5 == 0 && h6 == 0) ___Que = Que(
            "Bát Thuần Khôn",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6,
//            "八 純 坤",
            "NGẠ HỔ ĐẮC THỰC",
            "A.Mùi",
            "A.Tỵ",
            "A.Mão",
            "Q.Sửu",
            "Q.Hợi",
            "Q.Dậu",
            "",
            "",
            0,
            0,
            6,
            "Khôn",
            "LX",
            giaique[63],
            context.getString(R.string.qkhonn),
            context.getString(R.string.qkhonn2),
            context.getString(R.string.qkhonn3),
            context.getString(R.string.qkhonn4),
            context.getString(R.string.qkhonn5),
            context.getString(R.string.qkhonn6),
        )
        if (h1 == 0 && h2 == 0 && h3 == 0 && h4 == 1 && h5 == 1 && h6 == 1) ___Que = Que(
            "Thiên Địa Bĩ",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6,
//            "天 地 否",
            "HỔ LẠC HÃM KHANH",
            "A.Mùi",
            "A.Tỵ",
            "A.Mão",
            "N.Ngọ",
            "N.Thân",
            "N.Tuất",
            "Tử G.Tí",
            "",
            1,
            0,
            3,
            "Càn",
            "LH",
            giaique[6],
            context.getString(R.string.qbi),
            context.getString(R.string.qbi2),
            context.getString(R.string.qbi3),
            context.getString(R.string.qbi4),
            context.getString(R.string.qbi5),
            context.getString(R.string.qbi6),
        )
        if (h1 == 0 && h2 == 0 && h3 == 0 && h4 == 1 && h5 == 1 && h6 == 0) ___Que = Que(
            "Trạch Địa Tụy",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6,
//            "澤 地 萃",
            "LÝ NGƯ HÓA LONG",
            "A.Mùi",
            "A.Tỵ",
            "A.Mão",
            "Đ.Hợi",
            "Đ.Dậu",
            "Đ.Mùi",
            "",
            "",
            0,
            0,
            2,
            "Đoài",
            "",
            giaique[13],
            context.getString(R.string.qtuy),
            context.getString(R.string.qtuy2),
            context.getString(R.string.qtuy3),
            context.getString(R.string.qtuy4),
            context.getString(R.string.qtuy5),
            context.getString(R.string.qtuy6),
        )
        if (h1 == 0 && h2 == 0 && h3 == 0 && h4 == 1 && h5 == 0 && h6 == 1) ___Que = Que(
            "Hỏa Địa Tấn",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6,
//            "火 地 晉",
            "SỬ ĐỊA ĐẮC KIM",
            "A.Mùi",
            "A.Tỵ",
            "A.Mão",
            "K.Dậu",
            "K.Mùi",
            "K.Tỵ",
            "Tử G.Tí",
            "",
            1,
            0,
            4,
            "Càn",
            "DH",
            giaique[20],
            context.getString(R.string.qtan),
            context.getString(R.string.qtan2),
            context.getString(R.string.qtan3),
            context.getString(R.string.qtan4),
            context.getString(R.string.qtan5),
            context.getString(R.string.qtan6),
        )
        if (h1 == 0 && h2 == 0 && h3 == 0 && h4 == 1 && h5 == 0 && h6 == 0) ___Que = Que(
            "Lôi Địa Dự",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6,
//            "雷 地 豫",
            "THANH LONG ĐẮC VỊ",
            "A.Mùi",
            "A.Tỵ",
            "A.Mão",
            "C.Ngọ",
            "C.Thân",
            "C.Tuất",
            "Phụ C.Tí",
            "",
            1,
            0,
            1,
            "Chấn",
            "LH",
            giaique[27],
            context.getString(R.string.qdu),
            context.getString(R.string.qdu2),
            context.getString(R.string.qdu3),
            context.getString(R.string.qdu4),
            context.getString(R.string.qdu5),
            context.getString(R.string.qdu6),
        )
        if (h1 == 0 && h2 == 0 && h3 == 0 && h4 == 0 && h5 == 1 && h6 == 1) ___Que = Que(
            "Phong Địa Quan",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6,
//            "風 地 觀",
            "HẠN BỒNG PHÙNG HÀ",
            "A.Mùi",
            "A.Tỵ",
            "A.Mão",
            "T.Mùi",
            "T.Tỵ",
            "T.Mão",
            "Tử G.Tí",
            "Huynh N.Thân",
            1,
            5,
            4,
            "Càn",
            "",
            giaique[34],
            context.getString(R.string.qquan),
            context.getString(R.string.qquan2),
            context.getString(R.string.qquan3),
            context.getString(R.string.qquan4),
            context.getString(R.string.qquan5),
            context.getString(R.string.qquan6),
        )
        if (h1 == 0 && h2 == 0 && h3 == 0 && h4 == 0 && h5 == 1 && h6 == 0) ___Que = Que(
            "Thủy Địa Tỷ",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6,
//            "風 地 觀",
            "THUẬN PHONG HÀNH THUYỀN",
            "A.Mùi",
            "A.Tỵ",
            "A.Mão",
            "M.Thân",
            "M.Tuất",
            "M.Tí",
            "",
            "",
            0,
            0,
            3,
            "Khôn",
            "QH",
            giaique[41],
            context.getString(R.string.qty),
            context.getString(R.string.qty2),
            context.getString(R.string.qty3),
            context.getString(R.string.qty4),
            context.getString(R.string.qty5),
            context.getString(R.string.qty6),
        )
        if (h1 == 0 && h2 == 0 && h3 == 0 && h4 == 0 && h5 == 0 && h6 == 1) ___Que = Que(
            "Sơn Địa Bác",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6,
//            "山 地 剝",
            "ƯNG THƯỚC ĐỒNG LÂM",
            "A.Mùi",
            "A.Tỵ",
            "A.Mão",
            "B.Tuất",
            "B.Tí",
            "B.Dần",
            "Huynh N.Thân",
            "",
            5,
            0,
            5,
            "Càn",
            "",
            giaique[48],
            context.getString(R.string.qbac),
            context.getString(R.string.qbac2),
            context.getString(R.string.qbac3),
            context.getString(R.string.qbac4),
            context.getString(R.string.qbac5),
            context.getString(R.string.qbac6),
        )
        if (h1 == 1 && h2 == 1 && h3 == 1 && h4 == 0 && h5 == 0 && h6 == 0) ___Que = Que(
            "Địa Thiên Thái",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6,
//            "地 天 泰"
            "HỈ BÁO TAM NGUYÊN",
            "G.Tí",
            "G.Dần",
            "G.Thìn",
            "Q.Sửu",
            "Q.Hợi",
            "Q.Dậu",
            "Phụ A.Tỵ",
            "",
            2,
            0,
            3,
            "Khôn",
            "LH",
            giaique[56],
            context.getString(R.string.qthai),
            context.getString(R.string.qthai2),
            context.getString(R.string.qthai3),
            context.getString(R.string.qthai4),
            context.getString(R.string.qthai5),
            context.getString(R.string.qthai6),
        )
        if (h1 == 1 && h2 == 1 && h3 == 1 && h4 == 1 && h5 == 1 && h6 == 1) ___Que = Que(
            "Bát Thuần Càn",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "八 純 乾"
            "KHỐN LONG ĐẮC THỦY",
            "G.Tí",
            "G.Dần",
            "G.Thìn",
            "N.Ngọ",
            "N.Thân",
            "N.Tuất",
            "",
            "",
            0,
            0,
            6,
            "Càn",
            "LX",
            giaique[7],
            context.getString(R.string.qcan),
            context.getString(R.string.qcan2),
            context.getString(R.string.qcan3),
            context.getString(R.string.qcan4),
            context.getString(R.string.qcan5),
            context.getString(R.string.qcan6),
        )
        if (h1 == 1 && h2 == 1 && h3 == 1 && h4 == 1 && h5 == 1 && h6 == 0) ___Que = Que(
            "Trạch Thiên Quải",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "澤 天 夬"
            "DU PHONG THOÁT VÕNG",
            "G.Tí",
            "G.Dần",
            "G.Thìn",
            "Đ.Hợi",
            "Đ.Dậu",
            "Đ.Mùi",
            "Phụ A.Tỵ",
            "",
            2,
            0,
            5,
            "Khôn",
            "",
            giaique[14],
            context.getString(R.string.qquai),
            context.getString(R.string.qquai2),
            context.getString(R.string.qquai3),
            context.getString(R.string.qquai4),
            context.getString(R.string.qquai5),
            context.getString(R.string.qquai6),///////////////////////
        )
        if (h1 == 1 && h2 == 1 && h3 == 1 && h4 == 1 && h5 == 0 && h6 == 1) ___Que = Que(
            "Hỏa Thiên Đại Hữu",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "火 天 大 有"
            "TRẢM THỤ MÔ TƯỚC",
            "G.Tí",
            "G.Dần",
            "G.Thìn",
            "K.Dậu",
            "K.Mùi",
            "K.Tỵ",
            "",
            "",
            0,
            0,
            3,
            "Càn",
            "QH",
            giaique[21],
            context.getString(R.string.qdaihuu),
            context.getString(R.string.qdaihuu2),
            context.getString(R.string.qdaihuu3),
            context.getString(R.string.qdaihuu4),
            context.getString(R.string.qdaihuu5),
            context.getString(R.string.qdaihuu6),
        )
        if (h1 == 1 && h2 == 1 && h3 == 1 && h4 == 1 && h5 == 0 && h6 == 0) ___Que = Que(
            "Lôi Thiên Đại Tráng",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "雷 天 大 壯"
            "CÔNG SƯ ĐẮC MỘC",
            "G.Tí",
            "G.Dần",
            "G.Thìn",
            "C.Ngọ",
            "C.Thân",
            "C.Tuất",
            "",
            "",
            0,
            0,
            4,
            "Khôn",
            "LX",
            giaique[28],
            context.getString(R.string.qdaitrang),
            context.getString(R.string.qdaitrang2),
            context.getString(R.string.qdaitrang3),
            context.getString(R.string.qdaitrang4),
            context.getString(R.string.qdaitrang5),
            context.getString(R.string.qdaitrang6),
        )
        if (h1 == 1 && h2 == 1 && h3 == 1 && h4 == 0 && h5 == 1 && h6 == 1) ___Que = Que(
            "Phong Thiên Tiểu Súc",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "風 天 小 畜"
            "MẬT VÂN BẤT VŨ",
            "G.Tí",
            "G.Dần",
            "G.Thìn",
            "T.Mùi",
            "T.Tỵ",
            "T.Mão",
            "Quan T.Dậu",
            "",
            3,
            0,
            1,
            "Tốn",
            "",
            giaique[35],
            context.getString(R.string.qtieusuc),
            context.getString(R.string.qtieusuc2),
            context.getString(R.string.qtieusuc3),
            context.getString(R.string.qtieusuc4),
            context.getString(R.string.qtieusuc5),
            context.getString(R.string.qtieusuc6),
        )
        if (h1 == 1 && h2 == 1 && h3 == 1 && h4 == 0 && h5 == 1 && h6 == 0) ___Que = Que(
            "Thủy Thiên Nhu",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "水 天 需"
            "MINH CHÂU XUẤT THỔ",
            "G.Tí",
            "G.Dần",
            "G.Thìn",
            "M.Thân",
            "M.Tuất",
            "M.Tí",
            "Phụ A.Tỵ",
            "",
            2,
            0,
            4,
            "Khôn",
            "DH",
            giaique[42],
            context.getString(R.string.qnhu),
            context.getString(R.string.qnhu2),
            context.getString(R.string.qnhu3),
            context.getString(R.string.qnhu4),
            context.getString(R.string.qnhu5),
            context.getString(R.string.qnhu6),
        )
        if (h1 == 1 && h2 == 1 && h3 == 1 && h4 == 0 && h5 == 0 && h6 == 1) ___Que = Que(
            "Sơn Thiên Đại Súc",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "山 天 大 畜"
            "TRẬN THẾ ĐẮC KHAI",
            "G.Tí",
            "G.Dần",
            "G.Thìn",
            "B.Tuất",
            "B.Tí",
            "B.Dần",
            "Phụ B.Ngọ",
            "Tử B.Thân",
            2,
            3,
            2,
            "Cấn",
            "",
            giaique[49],
            context.getString(R.string.qdaisuc),
            context.getString(R.string.qdaisuc2),
            context.getString(R.string.qdaisuc3),
            context.getString(R.string.qdaisuc4),
            context.getString(R.string.qdaisuc5),
            context.getString(R.string.qdaisuc6),
        )
        if (h1 == 1 && h2 == 1 && h3 == 0 && h4 == 0 && h5 == 0 && h6 == 0) ___Que = Que(
            "Địa Trạch Lâm",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "地 澤 臨"
            "PHÁT CHÍNH THI NHÂN",
            "Đ.Tỵ",
            "Đ.Mão",
            "Đ.Sửu",
            "Q.Sửu",
            "Q.Hợi",
            "Q.Dậu",
            "",
            "",
            0,
            0,
            2,
            "Khôn",
            "",
            giaique[57],
            context.getString(R.string.qlam),
            context.getString(R.string.qlam2),
            context.getString(R.string.qlam3),
            context.getString(R.string.qlam4),
            context.getString(R.string.qlam5),
            context.getString(R.string.qlam6),
        )
        if (h1 == 1 && h2 == 1 && h3 == 0 && h4 == 1 && h5 == 1 && h6 == 1) ___Que = Que(
            "Thiên Trạch Lý",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "天 澤 履"
            "PHỤNG MINH KỲ SƠN",
            "Đ.Tỵ",
            "Đ.Mão",
            "Đ.Sửu",
            "N.Ngọ",
            "N.Thân",
            "N.Tuất",
            "Tài B.Tí",
            "",
            5,
            0,
            5,
            "Cấn",
            "",
            giaique[0],
            context.getString(R.string.qlyy),
            context.getString(R.string.qlyy2),
            context.getString(R.string.qlyy3),
            context.getString(R.string.qlyy4),
            context.getString(R.string.qlyy5),
            context.getString(R.string.qlyy6),
        )//
        if (h1 == 1 && h2 == 1 && h3 == 0 && h4 == 1 && h5 == 1 && h6 == 0) ___Que = Que(
            "Bát Thuần Đoài",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "八 純 兌"
            "CHUẨN THỦY HÒA NÊ",
            "Đ.Tỵ",
            "Đ.Mão",
            "Đ.Sửu",
            "Đ.Hợi",
            "Đ.Dậu",
            "Đ.Mùi",
            "",
            "",
            0,
            0,
            6,
            "Đoài",
            "LX",
            giaique[15],
            context.getString(R.string.qdoai),
            context.getString(R.string.qdoai2),
            context.getString(R.string.qdoai3),
            context.getString(R.string.qdoai4),
            context.getString(R.string.qdoai5),
            context.getString(R.string.qdoai6),
        )
        if (h1 == 1 && h2 == 1 && h3 == 0 && h4 == 1 && h5 == 0 && h6 == 1) ___Que = Que(
            "Hỏa Trạch Khuê",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "火 澤 睽"
            "PHẢN MẠI TRƯ DƯƠNG",
            "Đ.Tỵ",
            "Đ.Mão",
            "Đ.Sửu",
            "K.Dậu",
            "K.Mùi",
            "K.Tỵ",
            "Tài B.Tí",
            "",
            5,
            0,
            4,
            "Cấn",
            "",
            giaique[22],
            context.getString(R.string.qkhue),
            context.getString(R.string.qkhue2),
            context.getString(R.string.qkhue3),
            context.getString(R.string.qkhue4),
            context.getString(R.string.qkhue5),
            context.getString(R.string.qkhue6),
        )
        if (h1 == 1 && h2 == 1 && h3 == 0 && h4 == 1 && h5 == 0 && h6 == 0) ___Que = Que(
            "Lôi Trạch Quy Muội",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "地 澤 臨"
            "DUYÊN MỘC CẦU NGƯ",
            "Đ.Tỵ",
            "Đ.Mão",
            "Đ.Sửu",
            "C.Ngọ",
            "C.Thân",
            "C.Tuất",
            "Tử Đ.Hợi",
            "",
            4,
            0,
            3,
            "Đoài",
            "QH",
            giaique[29],
            context.getString(R.string.qquimuoi),
            context.getString(R.string.qquimuoi2),
            context.getString(R.string.qquimuoi3),
            context.getString(R.string.qquimuoi4),
            context.getString(R.string.qquimuoi5),
            context.getString(R.string.qquimuoi6),
        )
        if (h1 == 1 && h2 == 1 && h3 == 0 && h4 == 0 && h5 == 1 && h6 == 1) ___Que = Que(
            "Phong Trạch Trung Phu",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "風 澤 中 孚"
            "HÀNH TẨU BẠC BĂNG",
            "Đ.Tỵ",
            "Đ.Mão",
            "Đ.Sửu",
            "T.Mùi",
            "T.Tỵ",
            "T.Mão",
            "Tử B.Thân",
            "Tài B.Tí",
            3,
            5,
            4,
            "Cấn",
            "DH",
            giaique[36],
            context.getString(R.string.qtrungphu),
            context.getString(R.string.qtrungphu2),
            context.getString(R.string.qtrungphu3),
            context.getString(R.string.qtrungphu4),
            context.getString(R.string.qtrungphu5),
            context.getString(R.string.qtrungphu6),
        )
        if (h1 == 1 && h2 == 1 && h3 == 0 && h4 == 0 && h5 == 1 && h6 == 0) ___Que = Que(
            "Thủy Trạch Tiết",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "水 澤 節"
            "TRẢM TƯỚNG PHONG THẦN",
            "Đ.Tỵ",
            "Đ.Mão",
            "Đ.Sửu",
            "M.Thân",
            "M.Tuất",
            "M.Tí",
            "",
            "",
            0,
            0,
            1,
            "Khảm",
            "LH",
            giaique[43],
            context.getString(R.string.qtiet),
            context.getString(R.string.qtiet2),
            context.getString(R.string.qtiet3),
            context.getString(R.string.qtiet4),
            context.getString(R.string.qtiet5),
            context.getString(R.string.qtiet6),
        )
        if (h1 == 1 && h2 == 1 && h3 == 0 && h4 == 0 && h5 == 0 && h6 == 1) ___Que = Que(
            "Sơn Trạch Tổn",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "山 澤 損"
            "THÔI XA PHÍ LỰC",
            "Đ.Tỵ",
            "Đ.Mão",
            "Đ.Sửu",
            "B.Tuất",
            "B.Tí",
            "B.Dần",
            "Tử B.Thân",
            "",
            3,
            0,
            3,
            "Cấn",
            "",
            giaique[50],
            context.getString(R.string.qtonn),
            context.getString(R.string.qtonn2),
            context.getString(R.string.qtonn3),
            context.getString(R.string.qtonn4),
            context.getString(R.string.qtonn5),
            context.getString(R.string.qtonn6),
        )
        if (h1 == 1 && h2 == 0 && h3 == 1 && h4 == 0 && h5 == 0 && h6 == 0) ___Que = Que(
            "Địa Hỏa Minh Di",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "地 火 明 夷"
            "QUÁ GIANG CHIẾT KIỀU",
            "K.Mão",
            "K.Sửu",
            "K.Hợi",
            "Q.Sửu",
            "Q.Hợi",
            "Q.Dậu",
            "Tài M.Ngọ",
            "",
            3,
            0,
            4,
            "Khảm",
            "DH",
            giaique[58],
            context.getString(R.string.qminhdi),
            context.getString(R.string.qminhdi2),
            context.getString(R.string.qminhdi3),
            context.getString(R.string.qminhdi4),
            context.getString(R.string.qminhdi5),
            context.getString(R.string.qminhdi6),
        )
        if (h1 == 1 && h2 == 0 && h3 == 1 && h4 == 1 && h5 == 1 && h6 == 1) ___Que = Que(
            "Thiên Hỏa Đồng Nhân",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "天 火 同 人"
            "TIÊN NHÂN CHỈ LỘ",
            "K.Mão",
            "K.Sửu",
            "K.Hợi",
            "N.Ngọ",
            "N.Thân",
            "N.Tuất",
            "",
            "",
            0,
            0,
            3,
            "Ly",
            "QH",
            giaique[1],
            context.getString(R.string.qdongnhan),
            context.getString(R.string.qdongnhan2),
            context.getString(R.string.qdongnhan3),
            context.getString(R.string.qdongnhan4),
            context.getString(R.string.qdongnhan5),
            context.getString(R.string.qdongnhan6),
        )
        if (h1 == 1 && h2 == 0 && h3 == 1 && h4 == 1 && h5 == 1 && h6 == 0) ___Que = Que(
            "Trạch Hỏa Cách",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "澤 火 革"
            "HẠN MIÊU ĐẮC VŨ",
            "K.Mão",
            "K.Sửu",
            "K.Hợi",
            "Đ.Hợi",
            "Đ.Dậu",
            "Đ.Mùi",
            "Tài M.Ngọ",
            "",
            3,
            0,
            4,
            "Khảm",
            "",
            giaique[8],
            context.getString(R.string.qcach),
            context.getString(R.string.qcach2),
            context.getString(R.string.qcach3),
            context.getString(R.string.qcach4),
            context.getString(R.string.qcach5),
            context.getString(R.string.qcach6),
        )
        if (h1 == 1 && h2 == 0 && h3 == 1 && h4 == 1 && h5 == 0 && h6 == 1) ___Que = Que(
            "Bát Thuần Ly",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "八 純 離"
            "THIÊN QUAN TỨ PHÚC",
            "K.Mão",
            "K.Sửu",
            "K.Hợi",
            "K.Dậu",
            "K.Mùi",
            "K.Tỵ",
            "",
            "",
            0,
            0,
            6,
            "Ly",
            "LX",
            giaique[23],
            context.getString(R.string.qly),
            context.getString(R.string.qly2),
            context.getString(R.string.qly3),
            context.getString(R.string.qly4),
            context.getString(R.string.qly5),
            context.getString(R.string.qly6),
        )
        if (h1 == 1 && h2 == 0 && h3 == 1 && h4 == 1 && h5 == 0 && h6 == 0) ___Que = Que(
            "Lôi Hỏa Phong",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "雷 火 豐"
            "CỔ KÍNH TRÙNG MINH",
            "K.Mão",
            "K.Sửu",
            "K.Hợi",
            "C.Ngọ",
            "C.Thân",
            "C.Tuất",
            "",
            "",
            0,
            0,
            5,
            "Khảm",
            "",
            giaique[30],
            context.getString(R.string.qphong),
            context.getString(R.string.qphong2),
            context.getString(R.string.qphong3),
            context.getString(R.string.qphong4),
            context.getString(R.string.qphong5),
            context.getString(R.string.qphong6),
        )
        if (h1 == 1 && h2 == 0 && h3 == 1 && h4 == 0 && h5 == 1 && h6 == 1) ___Que = Que(
            "Phong Hỏa Gia Nhân",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "風 火 家 人"
            "CẢNH LÝ QUAN HOA",
            "K.Mão",
            "K.Sửu",
            "K.Hợi",
            "T.Mùi",
            "T.Tỵ",
            "T.Mão",
            "Quan T.Dậu",
            "",
            3,
            0,
            2,
            "Tốn",
            "",
            giaique[37],
            context.getString(R.string.qgiainhan),
            context.getString(R.string.qgiainhan2),
            context.getString(R.string.qgiainhan3),
            context.getString(R.string.qgiainhan4),
            context.getString(R.string.qgiainhan5),
            context.getString(R.string.qgiainhan6),
        )
        if (h1 == 1 && h2 == 0 && h3 == 1 && h4 == 0 && h5 == 1 && h6 == 0) ___Que = Que(
            "Thủy Hỏa Ký Tế",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "水 火 既 濟"
            "KIM BẢNG ĐỀ DANH",
            "K.Mão",
            "K.Sửu",
            "K.Hợi",
            "M.Thân",
            "M.Tuất",
            "M.Tí",
            "Tài M.Ngọ",
            "",
            3,
            0,
            3,
            "Khảm",
            "",
            giaique[44],
            context.getString(R.string.qkite),
            context.getString(R.string.qkite2),
            context.getString(R.string.qkite3),
            context.getString(R.string.qkite4),
            context.getString(R.string.qkite5),
            context.getString(R.string.qkite6),
        )
        if (h1 == 1 && h2 == 0 && h3 == 1 && h4 == 0 && h5 == 0 && h6 == 1) ___Que = Que(
            "Sơn Hỏa Bí",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "山 火 賁"
            "HỈ KHÍ DOANH MÔN",
            "K.Mão",
            "K.Sửu",
            "K.Hợi",
            "B.Tuất",
            "B.Tí",
            "B.Dần",
            "Phụ B.Ngọ",
            "Tử B.Thân",
            2,
            3,
            1,
            "Cấn",
            "LH",
            giaique[51],
            context.getString(R.string.qbi),
            context.getString(R.string.qbi2),
            context.getString(R.string.qbi3),
            context.getString(R.string.qbi4),
            context.getString(R.string.qbi5),
            context.getString(R.string.qbi6),
        )
        if (h1 == 1 && h2 == 0 && h3 == 0 && h4 == 0 && h5 == 0 && h6 == 0) ___Que = Que(
            "Địa Lôi Phục",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "地 雷 復"
            "PHU THÊ PHẢN MỤC",
            "C.Tí",
            "C.Dần",
            "C.Thìn",
            "Q.Sửu",
            "Q.Hợi",
            "Q.Dậu",
            "Phụ A.Tỵ",
            "",
            2,
            0,
            1,
            "Khôn",
            "LH",
            giaique[59],
            context.getString(R.string.qphuc),
            context.getString(R.string.qphuc2),
            context.getString(R.string.qphuc3),
            context.getString(R.string.qphuc4),
            context.getString(R.string.qphuc5),
            context.getString(R.string.qphuc6),
        )
        if (h1 == 1 && h2 == 0 && h3 == 0 && h4 == 1 && h5 == 1 && h6 == 1) ___Que = Que(
            "Thiên Lôi Vô Vọng",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "天 雷 无 妄"
            "ĐIỂU BỊ LAO LUNG",
            "C.Tí",
            "C.Dần",
            "C.Thìn",
            "N.Ngọ",
            "N.Thân",
            "N.Tuất",
            "",
            "",
            0,
            0,
            4,
            "Tốn",
            "LX",
            giaique[2],
            context.getString(R.string.qvovong),
            context.getString(R.string.qvovong2),
            context.getString(R.string.qvovong3),
            context.getString(R.string.qvovong4),
            context.getString(R.string.qvovong5),
            context.getString(R.string.qvovong6),
        )
        if (h1 == 1 && h2 == 0 && h3 == 0 && h4 == 1 && h5 == 1 && h6 == 0) ___Que = Que(
            "Trạch Lôi Tùy",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "澤 雷 隨"
            "BỘ BỘ ĐĂNG CAO",
            "C.Tí",
            "C.Dần",
            "C.Thìn",
            "Đ.Hợi",
            "Đ.Dậu",
            "Đ.Mùi",
            "Tử C.Ngọ",
            "",
            4,
            0,
            3,
            "Chấn",
            "QH",
            giaique[9],
            context.getString(R.string.qtuyy),
            context.getString(R.string.qtuyy2),
            context.getString(R.string.qtuyy3),
            context.getString(R.string.qtuyy4),
            context.getString(R.string.qtuyy5),
            context.getString(R.string.qtuyy6),
        )
        if (h1 == 1 && h2 == 0 && h3 == 0 && h4 == 1 && h5 == 0 && h6 == 1) ___Que = Que(
            "Hỏa Lôi Phệ Hạp",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "火 雷 噬 嗑"
            "CƠ NHÂN NGỘ THỰC",
            "C.Tí",
            "C.Dần",
            "C.Thìn",
            "K.Dậu",
            "K.Mùi",
            "K.Tỵ",
            "",
            "",
            0,
            0,
            5,
            "Tốn",
            "",
            giaique[16],
            context.getString(R.string.qphehap),
            context.getString(R.string.qphehap2),
            context.getString(R.string.qphehap3),
            context.getString(R.string.qphehap4),
            context.getString(R.string.qphehap5),
            context.getString(R.string.qphehap6),
        )
        if (h1 == 1 && h2 == 0 && h3 == 0 && h4 == 1 && h5 == 0 && h6 == 0) ___Que = Que(
            "Bát Thuần Chấn",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "地 澤 臨"
            "KIM CHUNG DẠ TRÀNG",
            "C.Tí",
            "C.Dần",
            "C.Thìn",
            "C.Ngọ",
            "C.Thân",
            "C.Tuất",
            "",
            "",
            0,
            0,
            6,
            "Chấn",
            "LX",
            giaique[31],
            context.getString(R.string.qchan),
            context.getString(R.string.qchan2),
            context.getString(R.string.qchan3),
            context.getString(R.string.qchan4),
            context.getString(R.string.qchan5),
            context.getString(R.string.qchan6),
        )
        if (h1 == 1 && h2 == 0 && h3 == 0 && h4 == 0 && h5 == 1 && h6 == 1) ___Que = Que(
            "Phong Lôi Ích",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "風 雷 益"
            "KHÔ MỘC KHAI HOA",
            "C.Tí",
            "C.Dần",
            "C.Thìn",
            "T.Mùi",
            "T.Tỵ",
            "T.Mão",
            "Quan T.Dậu",
            "",
            3,
            0,
            3,
            "Tốn",
            "",
            giaique[38],
            context.getString(R.string.qich),
            context.getString(R.string.qich2),
            context.getString(R.string.qich3),
            context.getString(R.string.qich4),
            context.getString(R.string.qich5),
            context.getString(R.string.qich6),
        )
        if (h1 == 1 && h2 == 0 && h3 == 0 && h4 == 0 && h5 == 1 && h6 == 0) ___Que = Que(
            "Thủy Lôi Truân",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "水 雷 屯"
            "LOẠN TI VÔ ĐẦU",
            "C.Tí",
            "C.Dần",
            "C.Thìn",
            "M.Thân",
            "M.Tuất",
            "M.Tí",
            "Tài M.Ngọ",
            "",
            3,
            0,
            2,
            "Khảm",
            "",
            giaique[45],
            context.getString(R.string.qtruan),
            context.getString(R.string.qtruan2),
            context.getString(R.string.qtruan3),
            context.getString(R.string.qtruan4),
            context.getString(R.string.qtruan5),
            context.getString(R.string.qtruan6),
        )
        if (h1 == 1 && h2 == 0 && h3 == 0 && h4 == 0 && h5 == 0 && h6 == 1) ___Que = Que(
            "Sơn Lôi Di",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "山 雷 頤"
            "VỊ THỦY PHỎNG HIỀN",
            "C.Tí",
            "C.Dần",
            "C.Thìn",
            "B.Tuất",
            "B.Tí",
            "B.Dần",
            "Quan T.Dậu",
            "Tử T.Tỵ",
            3,
            5,
            4,
            "Tốn",
            "DH",
            giaique[52],
            context.getString(R.string.qdi),
            context.getString(R.string.qdi2),
            context.getString(R.string.qdi3),
            context.getString(R.string.qdi4),
            context.getString(R.string.qdi5),
            context.getString(R.string.qdi6),
        )
        if (h1 == 0 && h2 == 1 && h3 == 1 && h4 == 0 && h5 == 0 && h6 == 0) ___Que = Que(
            "Địa Phong Thăng",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "地 風 升"
            "CHỈ NHẬT CAO THĂNG",
            "T.Sửu",
            "T.Hợi",
            "T.Dậu",
            "Q.Sửu",
            "Q.Hợi",
            "Q.Dậu",
            "Đệ C.Dần",
            "Tử C.Ngọ",
            2,
            4,
            4,
            "Chấn",
            "",
            giaique[60],
            context.getString(R.string.qthang),
            context.getString(R.string.qthang2),
            context.getString(R.string.qthang3),
            context.getString(R.string.qthang4),
            context.getString(R.string.qthang5),
            context.getString(R.string.qthang6),
        )
        if (h1 == 0 && h2 == 1 && h3 == 1 && h4 == 1 && h5 == 1 && h6 == 1) ___Que = Que(
            "Thiên Phong Cấu",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "地 澤 臨"
            "THA HƯƠNG NGỘ HỮU",
            "T.Sửu",
            "T.Hợi",
            "T.Dậu",
            "N.Ngọ",
            "N.Thân",
            "N.Tuất",
            "Tài G.Dần",
            "",
            2,
            0,
            1,
            "Càn",
            "",
            giaique[3],
            context.getString(R.string.qcau),
            context.getString(R.string.qcau2),
            context.getString(R.string.qcau3),
            context.getString(R.string.qcau4),
            context.getString(R.string.qcau5),
            context.getString(R.string.qcau6),
        )//
        if (h1 == 0 && h2 == 1 && h3 == 1 && h4 == 1 && h5 == 1 && h6 == 0) ___Que = Que(
            "Trạch Phong Đại Quá",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "澤 風 大 過"
            "DẠ MỘNG KIM NGÂN",
            "T.Sửu",
            "T.Hợi",
            "T.Dậu",
            "Đ.Hợi",
            "Đ.Dậu",
            "Đ.Mùi",
            "Đệ C.Dần",
            "Tử C.Ngọ",
            2,
            4,
            4,
            "Chấn",
            "DH",
            giaique[10],
            context.getString(R.string.qdaiqua),
            context.getString(R.string.qdaiqua2),
            context.getString(R.string.qdaiqua3),
            context.getString(R.string.qdaiqua4),
            context.getString(R.string.qdaiqua5),
            context.getString(R.string.qdaiqua6),
        )
        if (h1 == 0 && h2 == 1 && h3 == 1 && h4 == 1 && h5 == 0 && h6 == 1) ___Que = Que(
            "Hỏa Phong Đỉnh",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "火 風 鼎"
            "NGƯ ÔNG ĐẮC LỢI",
            "T.Sửu",
            "T.Hợi",
            "T.Dậu",
            "K.Dậu",
            "K.Mùi",
            "K.Tỵ",
            "Phụ K.Mão",
            "",
            1,
            0,
            2,
            "Ly",
            "",
            giaique[17],
            context.getString(R.string.qdinh),
            context.getString(R.string.qdinh2),
            context.getString(R.string.qdinh3),
            context.getString(R.string.qdinh4),
            context.getString(R.string.qdinh5),
            context.getString(R.string.qdinh6),
        )
        if (h1 == 0 && h2 == 1 && h3 == 1 && h4 == 1 && h5 == 0 && h6 == 0) ___Que = Que(
            "Lôi Phong Hằng",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "雷 風 恆"
            "NGƯ LAI TRÀNG VÕNG",
            "T.Sửu",
            "T.Hợi",
            "T.Dậu",
            "C.Ngọ",
            "C.Thân",
            "C.Tuất",
            "Đệ C.Dần",
            "",
            2,
            0,
            3,
            "Chấn",
            "",
            giaique[24],
            context.getString(R.string.qhang),
            context.getString(R.string.qhang2),
            context.getString(R.string.qhang3),
            context.getString(R.string.qhang4),
            context.getString(R.string.qhang5),
            context.getString(R.string.qhang6),
        )
        if (h1 == 0 && h2 == 1 && h3 == 1 && h4 == 0 && h5 == 1 && h6 == 1) ___Que = Que(
            "Bát Thuần Tốn",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "八 純 巽"
            "CHÂU ĐẮC THUẬN PHONG",
            "T.Sửu",
            "T.Hợi",
            "T.Dậu",
            "T.Mùi",
            "T.Tỵ",
            "T.Mão",
            "",
            "",
            0,
            0,
            6,
            "Tốn",
            "LX",
            giaique[39],
            context.getString(R.string.qton),
            context.getString(R.string.qton2),
            context.getString(R.string.qton3),
            context.getString(R.string.qton4),
            context.getString(R.string.qton5),
            context.getString(R.string.qton6),
        )
        if (h1 == 0 && h2 == 1 && h3 == 1 && h4 == 0 && h5 == 1 && h6 == 0) ___Que = Que(
            "Thủy Phong Tỉnh",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "水 風 井"
            "KHÔ TỈNH SINH TUYỀN",
            "T.Sửu",
            "T.Hợi",
            "T.Dậu",
            "M.Thân",
            "M.Tuất",
            "M.Tí",
            "Đệ C.Dần",
            "Tử C.Ngọ",
            2,
            4,
            5,
            "Chấn",
            "",
            giaique[46],
            context.getString(R.string.qtinh),
            context.getString(R.string.qtinh2),
            context.getString(R.string.qtinh3),
            context.getString(R.string.qtinh4),
            context.getString(R.string.qtinh5),
            context.getString(R.string.qtinh6),
        )
        if (h1 == 0 && h2 == 1 && h3 == 1 && h4 == 0 && h5 == 0 && h6 == 1) ___Que = Que(
            "Sơn Phong Cổ",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "山 風 蠱"
            "THÔI MA PHẦN ĐẠO",
            "T.Sửu",
            "T.Hợi",
            "T.Dậu",
            "B.Tuất",
            "B.Tí",
            "B.Dần",
            "Tử T.Tỵ",
            "",
            5,
            0,
            3,
            "Tốn",
            "QH",
            giaique[53],
            context.getString(R.string.qco),
            context.getString(R.string.qco2),
            context.getString(R.string.qco3),
            context.getString(R.string.qco4),
            context.getString(R.string.qco5),
            context.getString(R.string.qco6),
        )
        if (h1 == 0 && h2 == 1 && h3 == 0 && h4 == 0 && h5 == 0 && h6 == 0) ___Que = Que(
            "Địa Thủy Sư",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "地 水 師"
            "MÃ ĐÁO THÀNH CÔNG",
            "M.Dần",
            "M.Thìn",
            "M.Ngọ",
            "Q.Sửu",
            "Q.Hợi",
            "Q.Dậu",
            "",
            "",
            0,
            0,
            3,
            "Khảm",
            "QH",
            giaique[61],
            context.getString(R.string.qsu),
            context.getString(R.string.qsu2),
            context.getString(R.string.qsu3),
            context.getString(R.string.qsu4),
            context.getString(R.string.qsu5),
            context.getString(R.string.qsu6),
        )
        if (h1 == 0 && h2 == 1 && h3 == 0 && h4 == 1 && h5 == 1 && h6 == 1) ___Que = Que(
            "Thiên Thủy Tụng",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "天 水 訟"
            "NHỊ NHÂN TRANH LỘ",
            "M.Dần",
            "M.Thìn",
            "M.Ngọ",
            "N.Ngọ",
            "N.Thân",
            "N.Tuất",
            "Quan K.Hợi",
            "",
            3,
            0,
            4,
            "Ly",
            "DH",
            giaique[4],
            context.getString(R.string.qtung),
            context.getString(R.string.qtung2),
            context.getString(R.string.qtung3),
            context.getString(R.string.qtung4),
            context.getString(R.string.qtung5),
            context.getString(R.string.qtung6),
        )//
        if (h1 == 0 && h2 == 1 && h3 == 0 && h4 == 1 && h5 == 1 && h6 == 0) ___Que = Que(
            "Trạch Thủy Khốn",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "澤 水 困"
            "THOÁT LÃNG TRỪU ĐÊ",
            "M.Dần",
            "M.Thìn",
            "M.Ngọ",
            "Đ.Hợi",
            "Đ.Dậu",
            "Đ.Mùi",
            "",
            "",
            0,
            0,
            1,
            "Đoài",
            "LH",
            giaique[11],
            context.getString(R.string.qkhon),
            context.getString(R.string.qkhon2),
            context.getString(R.string.qkhon3),
            context.getString(R.string.qkhon4),
            context.getString(R.string.qkhon5),
            context.getString(R.string.qkhon6),
        )
        if (h1 == 0 && h2 == 1 && h3 == 0 && h4 == 1 && h5 == 0 && h6 == 1) ___Que = Que(
            "Hỏa Thủy Vị Tế",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "火 水 未 濟"
            "TIỂU NHÂN HÃM HẠI",
            "M.Dần",
            "M.Thìn",
            "M.Ngọ",
            "K.Dậu",
            "K.Mùi",
            "K.Tỵ",
            "Quan K.Hợi",
            "",
            3,
            0,
            3,
            "Ly",
            "",
            giaique[18],
            context.getString(R.string.qvite),
            context.getString(R.string.qvite2),
            context.getString(R.string.qvite3),
            context.getString(R.string.qvite4),
            context.getString(R.string.qvite5),
            context.getString(R.string.qvite6),
        )
        if (h1 == 0 && h2 == 1 && h3 == 0 && h4 == 1 && h5 == 0 && h6 == 0) ___Que = Que(
            "Lôi Thủy Giải",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "雷 水 解"
            "NGŨ QUAN THOÁT NẠN",
            "M.Dần",
            "M.Thìn",
            "M.Ngọ",
            "C.Ngọ",
            "C.Thân",
            "C.Tuất",
            "Phụ C.Tí",
            "",
            1,
            0,
            2,
            "Chấn",
            "",
            giaique[25],
            context.getString(R.string.qgiai),
            context.getString(R.string.qgiai2),
            context.getString(R.string.qgiai3),
            context.getString(R.string.qgiai4),
            context.getString(R.string.qgiai5),
            context.getString(R.string.qgiai6),
        )
        if (h1 == 0 && h2 == 1 && h3 == 0 && h4 == 0 && h5 == 1 && h6 == 1) ___Que = Que(
            "Phong Thủy Hoán",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "風 水 渙"
            "CÁCH HÀ VỌNG KIM",
            "M.Dần",
            "M.Thìn",
            "M.Ngọ",
            "T.Mùi",
            "T.Tỵ",
            "T.Mão",
            "Quan K.Hợi",
            "Tài K.Dậu",
            3,
            4,
            5,
            "Ly",
            "",
            giaique[32],
            context.getString(R.string.qhoan),
            context.getString(R.string.qhoan2),
            context.getString(R.string.qhoan3),
            context.getString(R.string.qhoan4),
            context.getString(R.string.qhoan5),
            context.getString(R.string.qhoan6),
        )
        if (h1 == 0 && h2 == 1 && h3 == 0 && h4 == 0 && h5 == 1 && h6 == 0) ___Que = Que(
            "Bát Thuần Khảm",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "八 純 坎",
            "THỦY ĐỂ LAO NGUYỆT",
            "M.Dần",
            "M.Thìn",
            "M.Ngọ",
            "M.Thân",
            "M.Tuất",
            "M.Tí",
            "",
            "",
            0,
            0,
            6,
            "Khảm",
            "LX",
            giaique[47],
            context.getString(R.string.qkham),
            context.getString(R.string.qkham2),
            context.getString(R.string.qkham3),
            context.getString(R.string.qkham4),
            context.getString(R.string.qkham5),
            context.getString(R.string.qkham6),
        )
        if (h1 == 0 && h2 == 1 && h3 == 0 && h4 == 0 && h5 == 0 && h6 == 1) ___Que = Que(
            "Sơn Thủy Mông",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "山 水 蒙",
            "TIỂU QUỶ THÂU TIỀN",
            "M.Dần",
            "M.Thìn",
            "M.Ngọ",
            "B.Tuất",
            "B.Tí",
            "B.Dần",
            "Tài K.Dậu",
            "",
            4,
            0,
            4,
            "Ly",
            "",
            giaique[54],
            context.getString(R.string.qmong),
            context.getString(R.string.qmong2),
            context.getString(R.string.qmong3),
            context.getString(R.string.qmong4),
            context.getString(R.string.qmong5),
            context.getString(R.string.qmong6),
        )
        if (h1 == 0 && h2 == 0 && h3 == 1 && h4 == 0 && h5 == 0 && h6 == 0) ___Que = Que(
            "Địa Sơn Khiêm",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "地 山 謙",
            "NHỊ NHÂN PHÂN KIM",
            "B.Thìn",
            "B.Ngọ",
            "B.Thân",
            "Q.Sửu",
            "Q.Hợi",
            "Q.Dậu",
            "Tài Đ.Mão",
            "",
            2,
            0,
            5,
            "Đoài",
            "",
            giaique[62],
            context.getString(R.string.qkhiem),
            context.getString(R.string.qkhiem2),
            context.getString(R.string.qkhiem3),
            context.getString(R.string.qkhiem4),
            context.getString(R.string.qkhiem5),
            context.getString(R.string.qkhiem6),
        )
        if (h1 == 0 && h2 == 0 && h3 == 1 && h4 == 1 && h5 == 1 && h6 == 1) ___Que = Que(
            "Thiên Sơn Độn",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "天 山 遯",
            "NÙNG VÂN TẾ NHẬT",
            "B.Thìn",
            "B.Ngọ",
            "B.Thân",
            "N.Ngọ",
            "N.Thân",
            "N.Tuất",
            "Tử G.Tí",
            "Tài G.Dần",
            1,
            2,
            2,
            "Càn",
            "",
            giaique[5],
            context.getString(R.string.qdon),
            context.getString(R.string.qdon2),
            context.getString(R.string.qdon3),
            context.getString(R.string.qdon4),
            context.getString(R.string.qdon5),
            context.getString(R.string.qdon6),
        )//
        if (h1 == 0 && h2 == 0 && h3 == 1 && h4 == 1 && h5 == 1 && h6 == 0) ___Que = Que(
            "Trạch Sơn Hàm",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "澤 山 咸",
            "MANH NHA XUẤT THỔ",
            "B.Thìn",
            "B.Ngọ",
            "B.Thân",
            "Đ.Hợi",
            "Đ.Dậu",
            "Đ.Mùi",
            "Tài Đ.Mão",
            "",
            2,
            0,
            3,
            "Đoài",
            "",
            giaique[12],
            context.getString(R.string.qham),
            context.getString(R.string.qham2),
            context.getString(R.string.qham3),
            context.getString(R.string.qham4),
            context.getString(R.string.qham5),
            context.getString(R.string.qham6),
        )
        if (h1 == 0 && h2 == 0 && h3 == 1 && h4 == 1 && h5 == 0 && h6 == 1) ___Que = Que(
            "Hỏa Sơn Lữ",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "火 山 旅",
            "TÚC ĐIỂU PHẦN SÀO",
            "B.Thìn",
            "B.Ngọ",
            "B.Thân",
            "K.Dậu",
            "K.Mùi",
            "K.Tỵ",
            "Phụ K.Mão",
            "Quan K.Hợi",
            1,
            3,
            1,
            "Ly",
            "LH",
            giaique[19],
            context.getString(R.string.qlu),
            context.getString(R.string.qlu2),
            context.getString(R.string.qlu3),
            context.getString(R.string.qlu4),
            context.getString(R.string.qlu5),
            context.getString(R.string.qlu6),
        )
        if (h1 == 0 && h2 == 0 && h3 == 1 && h4 == 1 && h5 == 0 && h6 == 0) ___Que = Que(
            "Lôi Sơn Tiểu Quá",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "雷 山 小 過",
            "CẤP QUÁ ĐỘC KIỀU",
            "B.Thìn",
            "B.Ngọ",
            "B.Thân",
            "C.Ngọ",
            "C.Thân",
            "C.Tuất",
            "Tài Đ.Mão",
            "Tử Đ.Hợi",
            2,
            4,
            4,
            "Đoài",
            "DH",
            giaique[26],
            context.getString(R.string.qtieuqua),
            context.getString(R.string.qtieuqua2),
            context.getString(R.string.qtieuqua3),
            context.getString(R.string.qtieuqua4),
            context.getString(R.string.qtieuqua5),
            context.getString(R.string.qtieuqua6),
        )
        if (h1 == 0 && h2 == 0 && h3 == 1 && h4 == 0 && h5 == 1 && h6 == 1) ___Que = Que(
            "Phong Sơn Tiệm",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "風 山 漸",
            "TUẤN MÃ XUẤT LUNG",
            "B.Thìn",
            "B.Ngọ",
            "B.Thân",
            "T.Mùi",
            "T.Tỵ",
            "T.Mão",
            "Tài B.Tí",
            "",
            5,
            0,
            3,
            "Cấn",
            "QH",
            giaique[33],
            context.getString(R.string.qtiem),
            context.getString(R.string.qtiem2),
            context.getString(R.string.qtiem3),
            context.getString(R.string.qtiem4),
            context.getString(R.string.qtiem5),
            context.getString(R.string.qtiem6),
        )
        if (h1 == 0 && h2 == 0 && h3 == 1 && h4 == 0 && h5 == 1 && h6 == 0) ___Que = Que(
            "Thủy Sơn Kiển",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "水 山 蹇",
            "VŨ TUYẾT TẢI ĐỒ",
            "B.Thìn",
            "B.Ngọ",
            "B.Thân",
            "M.Thân",
            "M.Tuất",
            "M.Tí",
            "Tài Đ.Mão",
            "",
            2,
            0,
            4,
            "Đoài",
            "",
            giaique[40],
            context.getString(R.string.qkien),
            context.getString(R.string.qkien2),
            context.getString(R.string.qkien3),
            context.getString(R.string.qkien4),
            context.getString(R.string.qkien5),
            context.getString(R.string.qkien6),
        )
        if (h1 == 0 && h2 == 0 && h3 == 1 && h4 == 0 && h5 == 0 && h6 == 1) ___Que = Que(
            "Bát Thuần Cấn",
            h1,
            h2,
            h3,
            h4,
            h5,
            h6, 
//            "八 純 艮",
            "NHÂN ĐOẢN TÁO CAO",
            "B.Thìn",
            "B.Ngọ",
            "B.Thân",
            "B.Tuất",
            "B.Tí",
            "B.Dần",
            "",
            "",
            0,
            0,
            6,
            "Cấn",
            "LX",
            giaique[55],
            context.getString(R.string.qcann),
            context.getString(R.string.qcann2),
            context.getString(R.string.qcann3),
            context.getString(R.string.qcann4),
            context.getString(R.string.qcann5),
            context.getString(R.string.qcann6),
        )
        return ___Que
    }
}

@Parcelize
data class haodong(
    var hd1: Int,
    var hd2: Int,
    var hd3: Int,
    var hd4: Int,
    var hd5: Int,
    var hd6: Int
) : Parcelable

@Parcelize
data class chuoique(
    var h1: Int,
    var h2: Int,
    var h3: Int,
    var h4: Int,
    var h5: Int,
    var h6: Int,
) : Parcelable

data class checkedt(
    val edty: TextView,
    val edtt: TextView,
    val edtd: TextView,
    val edtg: TextView,
    val edtp: TextView,
    val edtnamxem: EditText?
) {
    fun IF(): Boolean {
        if (edty.text.toString() == "") {
            edty.error = "Bạn chưa nhập năm"
            return false
        }
        if (edtt.text.toString() == "") {
            edtt.error = "Bạn chưa nhập tháng"
            return false
        }
        if (edtd.text.toString() == "") {
            edtd.error = "Bạn chưa nhập ngày"
            return false
        }
        if (edtg.text.toString() == "") {
            edtg.error = "Bạn chưa nhập giờ"
            return false
        }
        if (edtp.text.toString() == "") {
            edtp.error = "Bạn chưa nhập phút"
            return false
        }
        if (edtnamxem?.text.toString() == "") {
            edtnamxem?.error = "Bạn chưa nhập năm xem"
            return false
        }
        return true
    }
}