name: Build iOS Framework

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch: # Nút bấm build thủ công trên web

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Loại bỏ cảnh báo Node.js 20

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build iOS Framework (Arm64)
      run: ./gradlew :shared:assembleSharedReleaseFrameworkIosArm64

    - name: Build iOS Framework (Simulator)
      run: ./gradlew :shared:assembleSharedReleaseFrameworkIosSimulatorArm64

    - name: Upload Framework Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-frameworks
        path: |
          shared/build/bin/iosArm64/releaseFramework/shared.framework
          shared/build/bin/iosSimulatorArm64/releaseFramework/shared.framework
        if-no-files-found: error
